#=============================================================================
# Project settings
#=============================================================================

# Only build master and develop on push; do not build every branch.
branches:
  only:
    - morse-develop

#=============================================================================
# Environment
#=============================================================================
# Use new Travis infrastructure (Docker can't sudo yet)
language: python
os: linux
dist: trusty
sudo: false

# Docs need graphviz to build
addons:
  apt:
    packages:
      - gfortran
      - mercurial
      - graphviz
      - gnupg2
      - libboost-dev

# Work around Travis's lack of support for Python on OSX
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew ls --versions python > /dev/null || brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew ls --versions gcc    > /dev/null || brew install gcc;    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew ls --versions gnupg2 > /dev/null || brew install gnupg2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi

# Install various dependencies
install:
  - pip install --upgrade pip
  - pip install --upgrade six
  - pip install --upgrade setuptools
  - pip install --upgrade codecov
  - pip install --upgrade flake8

before_script:
  # Need this to be able to compute the list of changed files
  - git fetch origin morse-develop:morse-develop

#=============================================================================
# Building
#=============================================================================

# Build matrix using the environment
# SPEC to specify the spack 'spec' to install
#env:
#  - SPEC=fxt
#  - SPEC=hwloc
#  - SPEC=simgrid
#  - SPEC=starpu
#script:
#  - echo -en 'travis_fold:start:run-build-morse\\r'
#  - share/spack/qa/run-build-morse
#  - echo -en 'travis_fold:end:run-build-morse\\r'

# First build misc libraries
jobs:
  include:
    - stage: misc
      - env: SPEC=fxt
      - env: SPEC=hwloc
    - stage: runtime
      - env: SPEC=starpu

script:
  - echo -en 'travis_fold:start:run-build-morse\\r'
  - share/spack/qa/run-build-morse
  - echo -en 'travis_fold:end:run-build-morse\\r'

# use stages to setup a pipeline
# build 1. misc libs 2. runtime libs 3. etc
#jobs:
#  include:
#    - stage: misc
#      env: SPEC='fxt'
#      script: share/spack/qa/run-build-morse
#      env: SPEC='hwloc'
#      script: share/spack/qa/run-build-morse
#    - stage: runtime
#      env: SPEC='starpu'
#      script: share/spack/qa/run-build-morse

after_success:
  - #codecov --env PY_VERSION

#=============================================================================
# Notifications
#=============================================================================
notifications:
  email:
    recipients: florent.pruvost@inria.fr
    on_success: change
    on_failure: always
